name: Create Azure Resources

on:
  push:
   paths:
     - 'bicep/**'
     - '.github/workflows/infra.yml'
  workflow_dispatch:    

env:
  RG_NAME: 'rg-logic-app-private'
  LOCATION: 'canadacentral'

jobs:
  create-azure-resources:

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Create Azure Resource Group
        run: |
          az group create --name ${{ env.RG_NAME }} --location ${{ env.LOCATION }}

      - name: deploy
        id: createResources
        uses: azure/arm-deploy@v1
        with:          
          resourceGroupName: ${{ env.RG_NAME }}
          template: ./bicep/main.bicep
          parameters: adminUsername=${{ secrets.ADMIN_USERNAME }} adminPassword=${{ secrets.ADMIN_PASSWORD }}   
          